### ISSUE TITLE
Sharing itinerary

### ISSUE THREAD

**Issue by UofTTeam2** [UofTTeam2/TravIS#8] opened 2023-10-17 05:36 UTC
# User Story

**As** a frequent traveler, 
**I want** to be able to create and manage my trip itineraries easily using the TravIs application,
**so that** I can efficiently plan and organize my travels.

---

### Travel Community and Social Features

- **Given** that I have created a trip,
- **When** I choose to share my itinerary with others,
- **Then** I should be able to share it via a unique link or invite specific users to view it.

**Comment by average-kirigiri-enjoyer** [comment] 2023-10-23 16:28
in handlebars;
- [x] Add little gear icon or something like that in the top right of the view page (alongside 'edit' button)
- [x] Create a 'public-view-itinerary' page, which is a duplicate of the 'view-itinerary' page, but without the 'gear' icon & the 'edit' button

in (public) javascript
- [x] Clicking the 'gear' icon causes a modal to pop up, displaying a text element with a link (/trips/public-view/[current trip ID]), and a 'switch' to make the itinerary page public
  - [x] Off by default, when switched on, sends a POST request (/api/trips/change-public) containing the current trip ID to update the 'public' field of the current trip to 'true'
  - [x] Similar POST request to set the 'public' field to 'false' when switched off

in (controller) javascript;
- [x] GET route (/trips/public-view/:id) uses authentication middleware described below, which, if passed, renders the 'public-view-itinerary' page of the appropriate trip using the route parameter ':id'
- [x] API POST route (/api/trips/change-public) retrieves trip_id (number) & public (boolean) from req.body, uses it to update the 'public' field of the trip with the matching 'id'

in utils;
- [x] Create authentication middleware to check if the trip the user is currently trying to access has a 'public' field = true
  - [x] If it is true, continue with the routing process. If it is false, redirect to the 'bad request' page

in models;
- [x] Add a 'public' field to the 'Trip' model (boolean, not null, default: false)

**Closed as completed** 2023-10-24 21:58 UTC
Labels: documentation, enhancement
